# fly.toml app configuration file for working-panda unified deployment
# Serves server-panda (Express), client-panda (React), and landing-panda (Astro)
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'working-panda-unified'
primary_region = 'jnb'

[build]
# Build context is now at repository root level
dockerfile = "Dockerfile"

[env]
PORT = "3001"
NODE_ENV = "production"

[http_service]
internal_port = 3001
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

# Health check configuration for unified app
[http_service.checks]
[http_service.checks.health]
grace_period = "10s"
interval = "30s"
method = "GET"
path = "/api/health"
protocol = "http"
timeout = "5s"
tls_skip_verify = false

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

# Resource monitoring and optimization
[metrics]
port = 9091
path = "/metrics"

# Deploy configuration
[deploy]
release_command = "echo 'Unified working-panda deployment ready'"
strategy = "rolling"

# Process configuration for unified app
[processes]
app = "node build/index.js"

# Scaling configuration
[auto_scaling]
min_machines = 0
max_machines = 3
