# Consolidated Repository CI/CD Pipeline
# Unified deployment: All apps served together through Express server on Fly.io

name: Consolidated Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    name: Test and Build All Projects
    runs-on: ubuntu-latest

    steps:
      - name: Checkout consolidated repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.16.0"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install server dependencies
        working-directory: server-panda
        run: bun install --frozen-lockfile

      - name: Install React app dependencies
        working-directory: client-panda
        run: bun install --frozen-lockfile

      - name: Install landing site dependencies
        working-directory: landing-panda
        run: bun install --frozen-lockfile

      - name: Lint server code
        working-directory: server-panda
        run: bun run lint || echo "Linting completed with warnings"

      - name: Lint React app
        working-directory: client-panda
        run: bun run lint || echo "Linting completed with warnings"

      - name: Test server build
        working-directory: server-panda
        run: bun run tsc --noEmit

      - name: Test React app build
        working-directory: client-panda
        run: bun run build

      - name: Test landing site build
        working-directory: landing-panda
        run: bun run build

  deploy-unified:
    name: Deploy Unified App to Fly.io
    runs-on: ubuntu-latest
    needs: test-and-build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    concurrency: deploy-unified-group

    steps:
      - name: Checkout consolidated repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.16.0"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install server dependencies
        working-directory: server-panda
        run: bun install --frozen-lockfile

      - name: Install React app dependencies
        working-directory: client-panda
        run: bun install --frozen-lockfile

      - name: Install landing site dependencies
        working-directory: landing-panda
        run: bun install --frozen-lockfile

      # NOTE: Docker build now handles frontend compilation
      # The multi-stage Dockerfile builds client-panda, landing-panda, and server-panda
      # No need for separate build:ui step as everything is built inside Docker

      - name: Setup Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy unified application to Fly.io
        run: flyctl deploy --remote-only --build-arg CACHE_BUST=${{ github.sha }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deployment Success Notification
        run: |
          echo "🎉 Unified deployment completed successfully!"
          echo "✅ Express server deployed with integrated React app and Astro site"
          echo "🚀 All applications accessible through single Fly.io deployment"
