# Consolidated Repository CI/CD Pipeline
# Unified deployment: All apps served together through Express server on Fly.io

name: Consolidated Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    name: Test and Build All Projects
    runs-on: ubuntu-latest

    steps:
      - name: Checkout consolidated repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.16.0"
          cache: "yarn"
          cache-dependency-path: |
            server-panda/yarn.lock
            a-working-panda/yarn.lock
            landing-panda/yarn.lock

      - name: Install server dependencies
        working-directory: server-panda
        run: yarn install --frozen-lockfile

      - name: Install React app dependencies
        working-directory: a-working-panda
        run: yarn install --frozen-lockfile

      - name: Install landing site dependencies
        working-directory: landing-panda
        run: yarn install --frozen-lockfile

      - name: Lint server code
        working-directory: server-panda
        run: yarn lint || echo "Linting completed with warnings"

      - name: Lint React app
        working-directory: a-working-panda
        run: yarn lint || echo "Linting completed with warnings"

      - name: Test server build
        working-directory: server-panda
        run: yarn tsc --noEmit

      - name: Test React app build
        working-directory: a-working-panda
        run: yarn build

      - name: Test landing site build
        working-directory: landing-panda
        run: yarn build

  deploy-unified:
    name: Deploy Unified App to Fly.io
    runs-on: ubuntu-latest
    needs: test-and-build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    concurrency: deploy-unified-group

    steps:
      - name: Checkout consolidated repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.16.0"
          cache: "yarn"
          cache-dependency-path: |
            server-panda/yarn.lock
            a-working-panda/yarn.lock
            landing-panda/yarn.lock

      - name: Install server dependencies
        working-directory: server-panda
        run: yarn install --frozen-lockfile

      - name: Install React app dependencies
        working-directory: a-working-panda
        run: yarn install --frozen-lockfile

      - name: Install landing site dependencies
        working-directory: landing-panda
        run: yarn install --frozen-lockfile

      - name: Build and integrate UI apps into server
        working-directory: server-panda
        run: yarn build:ui

      - name: Setup Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy unified application to Fly.io
        working-directory: server-panda
        run: flyctl deploy --remote-only --build-arg CACHE_BUST=${{ github.sha }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deployment Success Notification
        run: |
          echo "🎉 Unified deployment completed successfully!"
          echo "✅ Express server deployed with integrated React app and Astro site"
          echo "🚀 All applications accessible through single Fly.io deployment"
