# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/
# Updated to build UI from separate repository

name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time

    steps:
      - uses: actions/checkout@v4
        with:
          path: server-panda
      - uses: actions/checkout@v4
        with:
          repository: Adrian-corp/a-working-panda
          path: a-working-panda
          token: ${{ secrets.PAT_TOKEN }}
      - uses: actions/checkout@v4
        with:
          repository: Adrian-corp/landing-panda
          path: landing-panda
          token: ${{ secrets.PAT_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: |
            server-panda/yarn.lock
            a-working-panda/yarn.lock
            landing-panda/yarn.lock
      - name: Install server dependencies
        working-directory: server-panda
        run: yarn install --frozen-lockfile
      - name: Install UI dependencies
        working-directory: a-working-panda
        run: yarn install --frozen-lockfile
      - name: Install landing page dependencies
        working-directory: landing-panda
        run: yarn install --frozen-lockfile
      - name: Build UI
        working-directory: server-panda
        run: yarn build:ui
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --build-arg CACHE_BUST=${{ github.sha }}
        working-directory: server-panda
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
